### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by minimario** [Some-random/theorem-proving-reasoning#1]
In Step 2, where is ```test_dataset_construction.py```?

**Comment by Some-random** [comment]
Sorry for the late reply! I've looked on my local machine and can't find the file. It was supposed to be in my local LeanDoJo folder, but it seems I only retained the files in my local Reprover folder after a server migration.

However, the file just reformats training data into the format required by ReProver, so it shouldn't be too difficult to recreate. Please let me know if you encounter any issues, and I can write a new one for you
